import { createElement } from "react";
import type { Metadata } from "next";
import type { Project } from "@/lib/projects";

export const SITE_URL = "https://remikarlin.com";
export const SITE_NAME = "Remi Karlin";

export const HOME_TITLE = "Remi Karlin — Filmmaker in Hong Kong and Paris";
export const HOME_DESCRIPTION =
  "Remi Karlin is a filmmaker and cinematographer between Hong Kong and Paris. Documentary, brand film and music video work, shot and graded end to end.";

/** Default share image, generated by app/opengraph-image.tsx (1200x630). */
export const DEFAULT_OG_IMAGE = "/opengraph-image";

export const PERSON_ID = `${SITE_URL}/#person`;
export const WEBSITE_ID = `${SITE_URL}/#website`;

/** Serialise JSON-LD safely for embedding inside a <script> tag. */
function safeJson(data: unknown): string {
  return JSON.stringify(data)
    .replace(/</g, "\\u003c");
}

/** A <script type="application/ld+json"> element. Usable from server components. */
export function jsonLdScript(data: unknown, key?: string | number) {
  return createElement("script", {
    key,
    type: "application/ld+json",
    dangerouslySetInnerHTML: { __html: safeJson(data) },
  });
}

export const siteJsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": WEBSITE_ID,
      url: `${SITE_URL}/`,
      name: SITE_NAME,
      alternateName: "remikarlin.com",
      inLanguage: "en",
      publisher: { "@id": PERSON_ID },
    },
    {
      "@type": "Person",
      "@id": PERSON_ID,
      name: SITE_NAME,
      alternateName: "Rémi Karlin",
      url: `${SITE_URL}/`,
      image: `${SITE_URL}/images/portrait.webp`,
      jobTitle: "Filmmaker, cinematographer and artistic director",
      description:
        "Filmmaker and cinematographer working between Hong Kong and Paris. Documentary, brand film and music video work, shot, edited and graded end to end.",
      knowsAbout: [
        "Cinematography",
        "Documentary film",
        "Music video",
        "Colour grading",
        "Art direction",
        "Brand identity",
      ],
      workLocation: [
        { "@type": "City", name: "Hong Kong" },
        { "@type": "City", name: "Paris" },
      ],
      affiliation: { "@type": "CollegeOrUniversity", name: "ESSEC Business School" },
      sameAs: [
        "https://www.instagram.com/karlinremi",
        "https://www.linkedin.com/in/remi-karlin",
        "https://www.youtube.com/@remicamm",
      ],
    },
  ],
};

type PageMetaInput = {
  title: string;
  description: string;
  /** Path starting with "/", used for canonical and og:url. */
  path: string;
  ogType?: "website" | "profile" | "video.other";
  /** Site-relative or absolute image URL. Defaults to the generated OG card. */
  image?: string;
  imageWidth?: number;
  imageHeight?: number;
  imageAlt?: string;
};

/**
 * Full per-page metadata. Next replaces (not merges) openGraph / twitter objects
 * from the layout, so every page builds the complete objects here.
 */
export function pageMeta({
  title,
  description,
  path,
  ogType = "website",
  image = DEFAULT_OG_IMAGE,
  imageWidth,
  imageHeight,
  imageAlt,
}: PageMetaInput): Metadata {
  const isDefault = image === DEFAULT_OG_IMAGE;
  const w = imageWidth ?? (isDefault ? 1200 : undefined);
  const h = imageHeight ?? (isDefault ? 630 : undefined);
  const alt = imageAlt ?? "Remi Karlin, filmmaker and cinematographer";
  const og =
    ogType === "profile"
      ? ({ type: "profile", firstName: "Remi", lastName: "Karlin" } as const)
      : ogType === "video.other"
        ? ({ type: "video.other" } as const)
        : ({ type: "website" } as const);

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      ...og,
      siteName: SITE_NAME,
      locale: "en_GB",
      url: path,
      title,
      description,
      images: [{ url: image, width: w, height: h, alt }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [{ url: image, alt }],
    },
  };
}

/** "/videos/solene-preview.mp4" -> "/videos/posters/solene-preview.webp" (1280x720). */
export function posterFor(previewVideo: string | undefined): string | undefined {
  if (!previewVideo) return undefined;
  const base = previewVideo.split("/").pop()?.replace(/\.[^.]+$/, "");
  return base ? `/videos/posters/${base}.webp` : undefined;
}

export const POSTER_WIDTH = 1280;
export const POSTER_HEIGHT = 720;

type ProjectSeo = { title: string; description: string };

const CREDIT = "Shot, edited and graded by Remi Karlin";

/** Hand-written titles and descriptions per project slug (audit section 2.2). */
const PROJECT_SEO: Record<string, ProjectSeo> = {
  "fan-yan": {
    title: "Fan Yan — Mini Documentary, Hong Kong | Remi Karlin",
    description:
      "A mini documentary portrait of Hong Kong artist Fan Yan, with artwork stills. Directed, shot, edited and graded by Remi Karlin in 2025.",
  },
  solene: {
    title: "Solène — 12:51 Cover, Music Video | Remi Karlin",
    description:
      "Music video for Solène's cover of 12:51 by The Strokes. Directed, shot, edited and graded by Remi Karlin in Philadelphia, 2025.",
  },
  "hong-kong": {
    title: "Hong Kong, City Portraits on Film | Remi Karlin",
    description: `Cinematic portraits of Hong Kong: Lantau, Sham Shui Po, the harbour and the cliffs. ${CREDIT}, 2025.`,
  },
  france: {
    title: "France — Travel Films, Chamonix to Avignon | Remi Karlin",
    description: `Travel cinematography across Chamonix, the South of France and Avignon. ${CREDIT}, 2025.`,
  },
  spain: {
    title: "Spain — Surf Trip Travel Film | Remi Karlin",
    description: `A surf trip along the northern coast of Spain. ${CREDIT}, 2025.`,
  },
  morocco: {
    title: "Morocco — Travel Film | Remi Karlin",
    description: `A short-form travel piece from a trip to Morocco. ${CREDIT}, 2025.`,
  },
  amsterdam: {
    title: "Amsterdam — Travel Film | Remi Karlin",
    description: `A short vlog-style edit from a trip to Amsterdam. ${CREDIT}, 2025.`,
  },
  vietnam: {
    title: "Vietnam — Travel Film | Remi Karlin",
    description: `A short reel from a trip to Vietnam. ${CREDIT}, 2025.`,
  },
  venice: {
    title: "Venice — Travel Film | Remi Karlin",
    description: `A short travel film from a trip to Venice. ${CREDIT}, 2025.`,
  },
  "new-york": {
    title: "New York — Travel Film | Remi Karlin",
    description: `A short travel film from a trip to New York. ${CREDIT}, 2025.`,
  },
  b1nbags: {
    title: "B1NBAGS — Brand Films, Hong Kong | Remi Karlin",
    description: `Brand films for B1NBAGS, a personal clothing brand started in Hong Kong in 2023. ${CREDIT}, 2023–25.`,
  },
  modessec: {
    title: "Modessec — Fashion Show Aftermovie | Remi Karlin",
    description: `Teaser and aftermovie for the Modessec fashion show at ESSEC, plus hoodie product photography. ${CREDIT}, Cergy, 2024–25.`,
  },
  rmx: {
    title: "RMX — DJ Association Films, ESSEC | Remi Karlin",
    description: `Films for the RMX DJ association at ESSEC, including an aftermovie. ${CREDIT}, Cergy, 2025.`,
  },
  ruinarktefact: {
    title: "Ruinarktefact — Campaign Direction, ESSEC | Remi Karlin",
    description:
      "Campaign films for Ruinarktefact at ESSEC, where Remi Karlin was artistic director and head of communications. Cergy, 2024–25.",
  },
};

/** ["Filmmaker","Editor","Art Director"] -> "Filmmaker, Editor & Art Director" */
function roleList(roles: string[]): string {
  if (roles.length <= 1) return roles.join("");
  return `${roles.slice(0, -1).join(", ")} & ${roles[roles.length - 1]}`;
}

export function getProjectSeo(p: Project): ProjectSeo {
  const known = PROJECT_SEO[p.slug];
  if (known) return known;
  if (p.agency) {
    // Agency work: "KFC — Havas Play, Filmmaker, Editor & Art Director | Remi Karlin"
    const roles = roleList(p.roles);
    const namesAgency = p.title.toLowerCase().includes(p.agency.name.toLowerCase());
    const who = [namesAgency ? "" : p.agency.name, roles].filter(Boolean).join(", ");
    return {
      title: `${p.title} — ${who} | ${SITE_NAME}`,
      description: `${p.shortDescription.replace(/\.$/, "")}. ${SITE_NAME}, ${roles || "work"}, at ${p.agency.name} in ${p.location || "Paris"}, ${p.year}.`,
    };
  }
  const format = p.subtitle.split("·")[0].trim();
  return {
    title: `${p.title} — ${format} | ${SITE_NAME}`,
    description: `${p.shortDescription.replace(/\.$/, "")}. ${CREDIT}, ${p.year}.`,
  };
}

/** Section a project's breadcrumb belongs to: the work index on the homepage. */
export function projectSection(_p: Project): { name: string; path: string } {
  return { name: "Work", path: "/#work" };
}
